HR.Web/Models/Company.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyId { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string RegNo { get; set; }
        public string CompanyLogo { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> InCorporationDate { get; set; }
        public string SSFNumber { get; set; }
        public string TaxIdNumber { get; set; }
        public string BranchCode { get; set; }
    }
}

HR.Web/Controllers/AdministrationController.cs
using HR.Web.BusinessObjects.LeaveMaster;
using HR.Web.BusinessObjects.Operation;
using HR.Web.BusinessObjects.Payroll;
using HR.Web.Models;
using HR.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HR.Web.Helpers;


namespace HR.Web.Controllers
{
    [SessionFilter]
    [ErrorHandler]
    public class AdministrationController : BaseController
    {
        AddressBO addressBO = null;
        CompanyBO companyBO = null;
        BranchBO branchBO = null;
        ContributionBO contributionBO = null;
        public AdministrationController()
        {
            addressBO = new AddressBO(SESSIONOBJ);
            companyBO = new CompanyBO(SESSIONOBJ);
            branchBO = new BranchBO(SESSIONOBJ);
            contributionBO = new ContributionBO(SESSIONOBJ);
        }
        // GET: Administration
        [HttpGet]
        public ActionResult Company(int companyId = 0)
        {
            CompanyVm companyvm = new CompanyVm();
            using (HrDataContext dbContext = new HrDataContext())
            {
                //companyId = dbContext.Branches.Where(x => x.BranchID == SESSIONOBJ.BRANCHID).FirstOrDefault()==null?0
                //    : dbContext.Branches.Where(x => x.BranchID == SESSIONOBJ.BRANCHID).FirstOrDefault().CompanyId.Value;
                companyId = 1000;
                Company company = dbContext.Companies.Where(x => x.CompanyId == companyId).FirstOrDefault();

                if (company != null)
                {
                    companyvm.company = new CompanyVmObj();
                    companyvm.company.CompanyCode = company.CompanyCode;
                    companyvm.company.CompanyId = company.CompanyId;
                    companyvm.company.CompanyName = company.CompanyName;
                    companyvm.company.CreatedBy = company.CreatedBy;
                    companyvm.company.CreatedOn = company.CreatedOn;
                    companyvm.company.InCorporationDate = company.InCorporationDate;
                    companyvm.company.IsActive = company.IsActive;
                    companyvm.company.ModifiedBy = company.ModifiedBy;
                    companyvm.company.ModifiedOn = company.ModifiedOn;
                    companyvm.company.RegNo = company.RegNo;
                    companyvm.company.SSFNo = company.SSFNumber;
                    companyvm.company.TaxIdNo = company.TaxIdNumber;
                    companyvm.company.BranchCode = company.BranchCode;


                }
                companyvm.companyAddress = new AddressVm();

                Address address = dbContext.Addresses.Where(x => x.LinkID == companyId && x.AddressType == UTILITY.COMPANY).FirstOrDefault();
                if (address != null)
                {
                    companyvm.companyAddress.Address1 = address.Address1;
                    companyvm.companyAddress.Address2 = address.Address2;
                    companyvm.companyAddress.AddressId = address.AddressId;
                    companyvm.companyAddress.AddressType = address.AddressType;
                    companyvm.companyAddress.CityName = address.CityName;
                    companyvm.companyAddress.Contact = address.Contact;
                    companyvm.companyAddress.CountryCode = address.CountryCode;
                    companyvm.companyAddress.CreatedBy = address.CreatedBy;
                    companyvm.companyAddress.CreatedOn = address.CreatedOn;
                    companyvm.companyAddress.Email = address.Email;
                    companyvm.companyAddress.FaxNo = address.FaxNo;
                    companyvm.companyAddress.IsActive = address.IsActive;
                    companyvm.companyAddress.LinkID = address.LinkID;
                    companyvm.companyAddress.MobileNo = address.MobileNo;
                    companyvm.companyAddress.ModifiedBy = address.ModifiedBy;
                    companyvm.companyAddress.ModifiedOn = address.ModifiedOn;
                    companyvm.companyAddress.SeqNo = address.SeqNo;
                    companyvm.companyAddress.StateName = address.StateName;
                    companyvm.companyAddress.TelNo = address.TelNo;
                    companyvm.companyAddress.WebSite = address.WebSite;
                    companyvm.companyAddress.ZipCode = address.ZipCode;
                }

                var result = dbContext.Companies.GroupJoin(dbContext.Branches,
                    a => a.CompanyId, b => b.CompanyId,
                            (a, b) => new { A = a, B = b }).ToList();
                companyvm.companyTreeVm = new List<companyTreeVm>();
                companyTreeVm companyTreeVm = new companyTreeVm();
                foreach (var item in result)
                {
                    companyTreeVm.href = item.A.CompanyId.ToString();
                    companyTreeVm.text = item.A.CompanyName;
                    companyTreeVm.nodes = new List<branchTreeVm>();
                    foreach (var subitem in item.B)
                    {
                        branchTreeVm branchVM = new branchTreeVm()
                        {
                            href = subitem.BranchID.ToString(),
                            text = subitem.BranchName,
                        };
                        companyTreeVm.nodes.Add(branchVM);
                    }
                }
                companyvm.companyTreeVm.Add(companyTreeVm);
            }

            return View(companyvm);
        }
        [HttpPost]
        public ActionResult Company(CompanyVm companyVM, AddressVm addressVm)
        {
            try
            {
                companyBO.SaveCompany(companyVM, addressVm);
            }
            catch (Exception ex)
            {

                throw ex;
            }

            return RedirectToAction("Company");
        }

        public ActionResult AddBranch(int branchId = 0)
        {
            BranchVm branchVm = new BranchVm();
            branchVm.address = new AddressVm();
            using (HrDataContext dbContext = new HrDataContext())
            {
                Branch branch = dbContext.Branches.Where(x => x.BranchID == branchId).FirstOrDefault();
                branchVm.branch = branch;
                Address address = dbContext.Addresses.Where(x => x.LinkID == branchId && x.AddressType == UTILITY.BRANCH).FirstOrDefault();

                if (branchId != -1 && address != null)
                {
                    branchVm.address.Address1 = address.Address1;
                    branchVm.address.Address2 = address.Address2;
                    branchVm.address.AddressId = address.AddressId;
                    branchVm.address.AddressType = address.AddressType;
                    branchVm.address.CityName = address.CityName;
                    branchVm.address.Contact = address.Contact;
                    branchVm.address.CountryCode = address.CountryCode;
                    branchVm.address.CreatedBy = address.CreatedBy;
                    branchVm.address.CreatedOn = address.CreatedOn;
                    branchVm.address.Email = address.Email;
                    branchVm.address.FaxNo = address.FaxNo;
                    branchVm.address.IsActive = address.IsActive;
                    branchVm.address.LinkID = address.LinkID;
                    branchVm.address.MobileNo = address.MobileNo;
                    branchVm.address.ModifiedBy = address.ModifiedBy;
                    branchVm.address.ModifiedOn = address.ModifiedOn;
                    branchVm.address.SeqNo = address.SeqNo;
                    branchVm.address.StateName = address.StateName;
                    branchVm.address.TelNo = address.TelNo;
                    branchVm.address.WebSite = address.WebSite;
                    branchVm.address.ZipCode = address.ZipCode;



                }



                var result = dbContext.Companies.GroupJoin(dbContext.Branches,
                    a => a.CompanyId, b => b.CompanyId,
                            (a, b) => new { A = a, B = b }).ToList();
                branchVm.companyTreeVm = new List<companyTreeVm>();
                companyTreeVm companyTreeVm = new companyTreeVm();
                foreach (var item in result)
                {
                    companyTreeVm.href = item.A.CompanyId.ToString();
                    companyTreeVm.text = item.A.CompanyName;
                    companyTreeVm.nodes = new List<branchTreeVm>();
                    foreach (var subitem in item.B)
                    {
                        branchTreeVm branchVM = new branchTreeVm()
                        {
                            href = subitem.BranchID.ToString(),
                            text = subitem.BranchName,
                        };
                        companyTreeVm.nodes.Add(branchVM);
                    }
                }
                branchVm.companyTreeVm.Add(companyTreeVm);
            }
            return View(branchVm);
        }

        [HttpPost]
        public ActionResult AddBranch(BranchVm branchVm, AddressVm addressVm)
        {

            try
            {
                branchBO.SaveBranch(branchVm, addressVm);
                //var list = contributionBO.GetListByProperty(x => (x.BranchId == branchVm.branch.BranchID) && (x.Name==UTILITY.BASICSALARYCOMPONENT)).ToList();
                //var count = list.Count();
                //if (count == 0)
                //{
                //    Contribution contribution = new Contribution
                //    {
                //        Name = UTILITY.BASICSALARYCOMPONENT,
                //        Description = UTILITY.BASICSALARYCOMPONENT,
                //        IsActive = true,
                //        CreatedBy = SESSIONOBJ.USERID,
                //        CreatedOn = UTILITY.SINGAPORETIME,
                //        RegisterCode = "PAYMENTS",
                //        BranchId = branchVm.branch.BranchID,

HR.Web/Views/Administration/AddBranch.cshtml
@model HR.Web.ViewModels.BranchVm
@section Styles{
    <style type="text/css">
        .icheckbox_flat {
            margin-top: -23px;
        }
    </style>
}
@using (Html.BeginForm("AddBranch", "Administration", FormMethod.Post, new
{ id = "frmBranch", name = "frmBranch", enctype = "multipart/form-data" })) { 
<div class="page">
    <div class="row">
        <div class="col-md-3">
            <div class="row">
                @{Html.RenderPartial("_TreeView", Model.companyTreeVm); }
            </div>
        </div>
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default panel-hovered panel-stacked mb10">
                        <div class="panel-heading">Branch</div>

                        <div class="panel-body">
                            <div class="row css5">
                                @Html.HiddenFor(x => x.branch.BranchID)
                                <div class="form-group">
                                    <label class="col-md-2 control-label">
                                        <span class="pull-right">Branch Code</span>
                                    </label>
                                    <div class="col-md-4">
                                        @Html.TextBoxFor(x => x.branch.BranchCode, new { @class = "form-control input-sm uppercase" })
                                    </div>
                                    <label class="col-md-2 control-label">
                                        <span class="pull-right">Branch Name</span>
                                    </label>
                                    <div class="col-md-4">
                                        @Html.TextBoxFor(x => x.branch.BranchName, new { @class = "form-control input-sm uppercase" })
                                    </div>                      
                                </div>
                            </div>
                            <div class="row css5">
                                <div class="form-group">
                                    <label class="col-md-2 control-label">
                                        <span class="pull-right">Registration No</span>
                                    </label>
                                    <div class="col-md-4">
                                        @Html.TextBoxFor(x => x.branch.RegNo, new { @class = "form-control input-sm uppercase" })
                                    </div>

                                    
                                        <div class="form-group">
                                            <label class="col-md-2 control-label">
                                                <span class="pull-right">Branch Tax Code</span>
                                            </label>
                                            <div class="col-md-4">
                                                @Html.TextBoxFor(x => x.branch.BranchTaxCode, new { @class = "form-control input-sm uppercase" })
                                            </div>
                                       
                                    </div>
                                </div>
                            </div>

                            <div class="row css5">

                                <div class="form-group">
                                    <label class="col-md-2 control-label">
                                        <span class="pull-right">SSF Number</span>
                                    </label>
                                    <div class="col-md-4">
                                        @Html.TextBoxFor(x => x.branch.SSFNumber, new { @class = "form-control input-sm uppercase" })
                                    </div>
                                    <label class="col-md-2 control-label">
                                        <span class="pull-right">Tax ID Number</span>
                                    </label>
                                    <div class="col-md-4">
                                        @Html.TextBoxFor(x => x.branch.TaxIdNumber, new { @class = "form-control input-sm uppercase" })
                                    </div>

                                </div>
                            </div>
                          

                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    @{Html.RenderPartial("_Address", Model.address);}
                </div>
            </div>
        </div>
    </div>
    

    

    <div class="row">
        <div class="col-md-12">
            <div>
                <button class="btn btn-primary btn-sm" type="button" onclick="SaveBranch()"><i class="fa fa-floppy-o" aria-hidden="true"></i>Save</button>
            </div>
        </div>
    </div>
</div>
}

@section Scripts{
    <script type="text/javascript">
        $(function () {
            $('#li_Admin').addClass('open');
            $('#li_company').addClass('active');
        });
            $('#frmBranch').validate({
                rules: {
                    'branch.BranchCode': {
                        required:true
                    },
                    'branch.BranchName': {
                        required: true
                    },
                    'branch.RegNo': {
                        required: true
                    },
                    //'company.InCorporationDate': {
                    //    required: true
                    //},
                    'Address1': {
                        required: true,
                        maxlength: 200
                    },
                    'CityName': {
                        required: true
                    },
                    'StateName': {
                        required: true
                    },
                    'CountryCode': {
                        required: true
                    },
                    'TelNo': {
                        required: true
                    },
                    'FaxNo': {
                        required: true
                    },
                    'MobileNo': {
                        required: true
                    },
                    'Contact': {
                        required: true
                    },
                    'Email': {
                        'email':true,
                        required: true
                    },
                }
            });
       
        function SaveBranch()
        {
            if ($('#frmBranch').valid()) {
                $('#frmBranch').submit();
                swal({
                    title: "Saved Successfully",
                    text: "",
                    closeOnConfirm: true,
                    confirmButtonText: "Ok",
                    confirmButtonClass: "btn-primary",
                    timer: 5000
                },
                                        function () {
                                            $.loader({
                                                className: "blue-with-image-2",
                                                content: '',
                                            });
                                        })
            }
            else {
                swal("Incorrect Inputs");
            }

        }
    </script>
}

HR.Web/Views/Administration/Company.cshtml
@model HR.Web.ViewModels.CompanyVm

@section Styles{
    <style type="text/css">
        .icheckbox_flat {
            margin-top: -23px;
        }
    </style>
}
@using (Html.BeginForm("Company", "Administration", FormMethod.Post, new
{ id = "frmCompany", name = "frmCompany", enctype = "multipart/form-data" }))
{
    <div class="page">
        <div class="row">
            <div class="col-md-3">
                <div class="row">
                    @{Html.RenderPartial("_TreeView", Model.companyTreeVm); }
                </div>
            </div>
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default panel-hovered panel-stacked mb10">
                            <div class="panel-heading">Company</div>
                                    <button type="button" onclick="location.href='@Url.Content("~/Administration/AddBranch?branchId=0" )'" class="btn btn-primary btn-sm pull-right">Add Branch</button>
                            @Html.HiddenFor(x => x.company.CompanyId)
                            <div class="panel-body">
                                <div class="row css5">

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">
                                            <span class="pull-right">Company Code</span>
                                        </label>
                                        <div class="col-md-3">
                                            @Html.TextBoxFor(x => x.company.CompanyCode, new { @class = "form-control input-sm uppercase", @maxlength="20" })
                                        </div>
                                        <label class="col-md-3 control-label">
                                            <span class="pull-right">Company Name</span>
                                        </label>
                                        <div class="col-md-3">
                                            @Html.TextBoxFor(x => x.company.CompanyName, new { @class = "form-control input-sm uppercase", @maxlength="200" })
                                        </div>
                                       
                                    </div>
                                </div>
                                <div class="row css5">
                                    <div class="form-group">
                                       
                                        <label class="col-md-3 control-label">
                                            <span class="pull-right">Registration No</span>
                                        </label>
                                        <div class="col-md-3">
                                            @Html.TextBoxFor(x => x.company.RegNo, new { @class = "form-control input-sm uppercase" })
                                        </div>
                                        <label class="col-md-3 control-label">
                                            <span class="pull-right">InCorporate Date</span>
                                        </label>
                                        <div class="col-md-3">
                                            <div class="input-group date dtCss" id="CorporationDate">
                                                @Html.TextBoxFor(x => x.company.InCorporationDate, new { @class = "form-control dtCssTxt input-sm" })
                                                <span class="input-group-addon">
                                                    <i class="ion ion-calendar"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                               
                                <div class="row css5">
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">
                                            <span class="pull-right">SSF Number</span>
                                        </label>
                                        <div class="col-md-3">
                                            @Html.TextBoxFor(x => x.company.SSFNo, new { @class = "form-control input-sm uppercase"})
                                        </div>
                                        <label class="col-md-3 control-label">
                                            <span class="pull-right">Tax ID Number</span>
                                        </label>
                                        <div class="col-md-3">
                                            @Html.TextBoxFor(x => x.company.TaxIdNo, new { @class = "form-control input-sm uppercase" })
                                        </div>

                                    </div>
                                </div>
                                <div class="row css5">
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">
                                            <span class="pull-right">Branch Code</span>
                                        </label>
                                        <div class="col-md-3">
                                            @Html.TextBoxFor(x => x.company.BranchCode, new { @class = "form-control input-sm uppercase" })
                                        </div>                                       
                                            <label class="col-md-3 control-label">
                                                <span class="pull-right">Logo</span>
                                            </label>
                                            <div class="col-md-3" style="margin-top:10px;">
                                                @Html.TextBoxFor(x => x.company.Logo, new { type = "file" })
                                            </div>                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        @{Html.RenderPartial("_Address", Model.companyAddress); }
                    </div>                    
                </div>
            </div>
        </div>
        
        

        

        <div class="row">
            <div class="col-md-12">
                <div>
                    <button class="btn btn-primary btn-sm" type="button" onclick="SaveCompany()"><i class="fa fa-floppy-o" aria-hidden="true"></i>Save</button>
                </div>
            </div>
        </div>
    </div>
            }

@section Scripts{
    <script type="text/javascript">
        $(function () {
            $('#li_Admin').addClass('open');
            $('#li_company').addClass('active');
            /*Tree View Starts*/


            /*Tree View Ends*/


            $('.dtCss').datetimepicker({
                icons: {
                    time: 'fa fa-clock-o',
                    date: 'fa fa-calendar',
                    up: 'fa fa-arrow-up',
                    down: 'fa fa-arrow-down',
                    previous: 'fa fa-arrow-left',
                    next: 'fa fa-arrow-right'
                },
                format: dateFormat
            });

            $('#frmCompany').validate({
                rules: {
                    'company.CompanyCode': {
                        required: true,
                        maxlength:20
                    },
                    'company.CompanyName': {
                        required: true,
                        maxlength:200
                    },
                    'company.RegNo': {
                        required: true
                    },
                    //'company.InCorporationDate': {
                    //    required: true
                    //},
                    'Address1': {
                        required: true,
                        maxlength:200
                    },
                    'CityName': {
                        required: true
                    },
                    'StateName': {
                        required: true
                    },
                    'CountryCode': {
                        required: true
                    },
                    'TelNo': {
                        required: true,
                    },
                    'FaxNo': {
                        required: true,
                    },
                    'MobileNo': {
                        required: true,
                        number: true
                    },
                    'Contact': {
                        required: true,
                        
                    },
                    'Email': {
                        'email': true,
                        required: true
                    },
                   
                }
            });
        })
        function SaveCompany() {
            if ($('#frmCompany').valid()) {
                $('#frmCompany').submit();
                swal({
                    title: "Saved Successfully",
                    text: "",
                    closeOnConfirm: true,
                    confirmButtonText: "Ok",
                    confirmButtonClass: "btn-primary",
                    timer: 5000
                },
                                         function () {
                                             $.loader({
                                                 className: "blue-with-image-2",
                                                 content: '',
                                             });
                                         })
            }
            else {
                swal("Incorrect Inputs");
            }

        }
    </script>
}