HR.Web/Models/Address.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressId { get; set; }
        public int LinkID { get; set; }
        public short SeqNo { get; set; }
        public string AddressType { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string CityName { get; set; }
        public string StateName { get; set; }
        public string CountryCode { get; set; }
        public string ZipCode { get; set; }
        public string TelNo { get; set; }
        public string FaxNo { get; set; }
        public string MobileNo { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int BranchId { get; set; }
    }
}

HR.Web/Models/EmployeeLeaveList.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaveList
    {
        public int EmployeeLeaveID { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public int BranchId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<decimal> Days { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int ManagerId { get; set; }
        public Nullable<decimal> LossOfPayDays { get; set; }
        public bool IsLossOfPay { get; set; }
        public string Session { get; set; }
    }
}

HR.Web/Controllers/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HR.Web.Helpers;

namespace HR.Web.Controllers
{
    [SessionFilter]
    [ErrorHandler]
    public class LayoutController : BaseController
    {
        // GET: Layout
        public PartialViewResult Links()
        {
            LayOutVM layoutVm = new LayOutVM()
            {
                RoleCode = ROLECODE,
                IsManager=ISMANAGER
            };
            return PartialView("_Links", layoutVm);
        }

        public class LayOutVM
        {
            public string RoleCode { get; set; }
            public bool IsManager { get; set; }
        }
    }
}

HR.Web/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
}

<div class="page">
    <div class="panel panel-default panel-hovered panel-stacked mb10">
        <div class="panel-heading">
            Sorry, Something Error has happened while processing.
            Please click the button to continue.

            <button type="button" class="btn btn-primary btn-sm" onclick="location.href='@Url.Content("~/Dashboard/Index")'">Back to DashBoard</button>
        </div>
        @*ViewBag.Msg*@
    </div>

</div>

HR.Web/Views/Shared/_Address.cshtml
@model HR.Web.ViewModels.AddressVm

<div class="panel panel-default panel-hovered panel-stacked mb10">
    <div class="panel-heading">Address</div>
    <div class="panel-body">
        <div class="row css5">
            <div class="form-group">
                <label class="col-md-2 control-label">
                    <span class="pull-right">Address1</span>
                </label>
                <div class="col-md-4">
                    @Html.TextAreaFor(x => x.Address1, new { @class = "form-control input-sm",@maxlength="200" })
                </div>
                <label class="col-md-2 control-label">
                    <span class="pull-right">Address2</span>
                </label>
                <div class="col-md-4">
                    @Html.TextAreaFor(x => x.Address2, new { @class = "form-control input-sm" })
                </div>
            </div>
        </div>

        <div class="row css5">
            <div class="form-group">
                <label class="col-md-2 control-label">
                    <span class="pull-right">Address3</span>
                </label>
                <div class="col-md-4">
                    @Html.TextAreaFor(x => x.Address3, new { @class = "form-control input-sm", @maxlength = "200" })
                </div>
                <label class="col-md-2 control-label">
                    <span class="pull-right">Address4</span>
                </label>
                <div class="col-md-4">
                    @Html.TextAreaFor(x => x.Address4, new { @class = "form-control input-sm" })
                </div>
            </div>
        </div>

        @*<div class="row css5">
            <div class="form-group">
                <label class="col-md-2 control-label">
                    <span class="pull-right">Address5</span>
                </label>
                <div class="col-md-4">
                    @Html.TextAreaFor(x => x.Address5, new { @class = "form-control input-sm", @maxlength = "200" })
                </div>
                <label class="col-md-2 control-label">
                    <span class="pull-right">Address6</span>
                </label>
                <div class="col-md-4">
                    @Html.TextAreaFor(x => x.Address6, new { @class = "form-control input-sm" })
                </div>
            </div>
        </div>

        <div class="row css5">
            <div class="form-group">
                <label class="col-md-2 control-label">
                    <span class="pull-right">Address7</span>
                </label>
                <div class="col-md-4">
                    @Html.TextAreaFor(x => x.Address7, new { @class = "form-control input-sm", @maxlength = "200" })
                </div>
                <label class="col-md-2 control-label">
                    <span class="pull-right">Address8</span>
                </label>
                <div class="col-md-4">
                    @Html.TextAreaFor(x => x.Address8, new { @class = "form-control input-sm" })
                </div>
            </div>
        </div>


        <div class="row css5">
            <div class="form-group">
                <label class="col-md-2 control-label">
                    <span class="pull-right">Address9</span>
                </label>
                <div class="col-md-4">
                    @Html.TextAreaFor(x => x.Address9, new { @class = "form-control input-sm", @maxlength = "200" })
                </div>
                <label class="col-md-2 control-label">
                    <span class="pull-right">Address10</span>
                </label>
                <div class="col-md-4">
                    @Html.TextAreaFor(x => x.Address10, new { @class = "form-control input-sm" })
                </div>
            </div>
        </div>


        <div class="row css5">
            <div class="form-group">
                <label class="col-md-2 control-label">
                    <span class="pull-right">Address11</span>
                </label>
                <div class="col-md-4">
                    @Html.TextAreaFor(x => x.Address11, new { @class = "form-control input-sm", @maxlength = "200" })
                </div>
                <label class="col-md-2 control-label">
                    <span class="pull-right">Address12</span>
                </label>
                <div class="col-md-4">
                    @Html.TextAreaFor(x => x.Address12, new { @class = "form-control input-sm" })
                </div>
            </div>
        </div>

        <div class="row css5">
            <div class="form-group">
                <label class="col-md-2 control-label">
                    <span class="pull-right">Address13</span>
                </label>
                <div class="col-md-4">
                    @Html.TextAreaFor(x => x.Address13, new { @class = "form-control input-sm", @maxlength = "200" })
                </div>
                <label class="col-md-2 control-label">
                    <span class="pull-right">City Name</span>
                </label>
                <div class="col-md-4">
                    @Html.TextBoxFor(x => x.CityName, new { @class = "form-control input-sm" })
                </div>
            </div>
        </div>*@

        <div class="row css5">
            <div class="form-group">
                <label class="col-md-2 control-label">
                    <span class="pull-right">City Name</span>
                </label>
                <div class="col-md-4">
                    @Html.TextBoxFor(x => x.CityName, new { @class = "form-control input-sm" })
                </div>
                <label class="col-md-2 control-label">
                    <span class="pull-right">State Name</span>
                </label>
                <div class="col-md-4">
                    @Html.TextBoxFor(x => x.StateName, new { @class = "form-control input-sm" })
                </div>
                
            </div>
        </div>

        <div class="row css5">
            <div class="form-group">
                <label class="col-md-2 control-label">
                    <span class="pull-right">Country Code</span>
                </label>
                <div class="col-md-4">
                    @Html.DropDownListFor(x => x.CountryCode, SelectListItemHelper.CountryList(),
                                   "--Select--", new { @class = "form-control input-sm" })
                </div>
                <label class="col-md-2 control-label">
                    <span class="pull-right">Zip Code</span>
                </label>
                <div class="col-md-4">
                    @Html.TextBoxFor(x => x.ZipCode, new { @class = "form-control number input-sm" })
                </div>
                
            </div>
        </div>

        <div class="row css5">
            <div class="form-group">
               
                <label class="col-md-2 control-label">
                    <span class="pull-right">Tel No</span>
                </label>
                <div class="col-md-4">
                    @Html.TextBoxFor(x => x.TelNo, new { @class = "form-control validatenumber input-sm" })
                </div>
                <label class="col-md-2 control-label">
                    <span class="pull-right">Fax No</span>
                </label>
                <div class="col-md-4">
                    @Html.TextBoxFor(x => x.FaxNo, new { @class = "form-control validatenumber input-sm" })
                </div>
               
            </div>
        </div>
        <div class="row css5">
            <div class="form-group">
                <label class="col-md-2 control-label">
                    <span class="pull-right">Mobile No</span>
                </label>
                <div class="col-md-4">
                    @Html.TextBoxFor(x => x.MobileNo, new { @class = "form-control validatenumber input-sm" })
                </div>
                <label class="col-md-2 control-label">
                    <span class="pull-right">Contact</span>
                </label>
                <div class="col-md-4">
                    @Html.TextBoxFor(x => x.Contact, new { @class = "form-control validatenumber input-sm" })
                </div>
                
            </div>
        </div>

        <div class="row css5">
            <div class="form-group">
                <label class="col-md-2 control-label">
                    <span class="pull-right">Email</span>
                </label>
                <div class="col-md-4">
                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control input-sm" })
                </div>
                <label class="col-md-2 control-label">
                    <span class="pull-right">WebSite</span>
                </label>
                <div class="col-md-4">
                    @Html.TextBoxFor(x => x.WebSite, new { @class = "form-control input-sm" })
                </div>
            </div>
        </div>


    </div>

</div>

HR.Web/Views/Shared/_AppliedLeaveList.cshtml
@model IEnumerable<HR.Web.ViewModels.AppliedLeaveListVm>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="page">
    <div class="page-wrap">
        <div class="panel panel-default">
            <div class="panel-group" id="accordionDemo">
                @for (var i = 0; i < Model.Count(); i++)
                {
                    <div class="panel panel-default ng-isolate-scope">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a href="#collapse@(i)" data-toggle="collapse" class="accordion-toggle" data-parent="#accordionDemo">@Model.ElementAt(i).BranchName</a>
                            </h4>
                        </div>
                        <div class="panel-collapse collapse in" id="collapse@(i)">
                            <div class="panel-body">
                                <div>
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th>EmployeeId</th>
                                                <th>From Date</th>
                                                <th>To Date</th>

                                            </tr>
                                        </thead>
                                        <tbody>
                                            @for (var j = 0; j < Model.ElementAt(i).employeeLeaveList.Count(); j++)
                                            {
                                                <tr>
                                                    <td>@Model.ElementAt(i).employeeLeaveList.ElementAt(j).EmployeeId</td>
                                                    <td>@Model.ElementAt(i).employeeLeaveList.ElementAt(j).FromDate</td>
                                                    <td>@Model.ElementAt(i).employeeLeaveList.ElementAt(j).ToDate</td>
                                                </tr>
                                            }
                                        </tbody>

                                    </table>
                                </div>

                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

HR.Web/Views/Shared/_AppliedLeaveListAdmin.cshtml
@model IEnumerable<HR.Web.Models.EmployeeLeaveList>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12" style="margin-top:65px;">

    <div class="panel-group" id="accordionDemo">
        <div class="panel panel-default ng-isolate-scope">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a href="#collapseOne" data-toggle="collapse" class="accordion-toggle" data-parent="#accordionDemo">Singapore</a>
                </h4>
            </div>
            <div class="panel-collapse collapse in" id="collapseOne">
                <div class="panel-body">
                    <div>
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>EmployeeId</th>
                                    <th>From Date</th>
                                    <th>To Date</th>

                                </tr>
                            </thead>
                            <tbody>
                                
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td>@item.EmployeeId</td>
                                        <td>@item.FromDate</td>
                                        <td>@item.ToDate</td>
                                    </tr>
                                    }
                                </tbody>

                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

HR.Web/Views/Shared/_EmployeeLeaveList.cshtml
@model IEnumerable<HR.Web.Models.EmployeeLeaveList>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page">
    <div class="page-wrap">
        <div class="panel panel-default">
            <div class="box">
                <div class="box-header">Employee Leave List</div>
                <div class="box-body">
                    <table class="table table-hover">
                        <thead><tr>
                            <th>EmployeeId</th>
                            <th>FromDate</th>
                                   <th>ToDate</th>
                            </tr></thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>@item.EmployeeId</td>
                                <td>@item.FromDate</td>
                                <td>@item.ToDate</td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

HR.Web/Views/Shared/_Layout.cshtml
@{
    var baseObj = new BaseController();
}﻿
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" http>
    <title>HR</title>
    <link rel="stylesheet" href="@Url.Content("~/Css/ionicons-2.0.1/css/ionicons.css")">
    <link rel="stylesheet" href="@Url.Content("~/Css/font-awesome-4.7.0/css/font-awesome.css")">
    @*<link rel="stylesheet" href="@Url.Content("~/Css/c3.css")">*@
    <link href="@Url.Content("~/Css/skins/flat/_all.css")" rel="stylesheet" />

    @*<link href="@Url.Content("~/Css/skins/flat/green.css")" rel="stylesheet" />*@
    <!-- Plugins -->
    @RenderSection("TopStyles", false)
    <link rel="stylesheet" href="@Url.Content("~/Css/waves.css")">
    <link rel="stylesheet" href="@Url.Content("~/Css/perfect-scrollbar.css")">
    <!-- Css/Less Stylesheets -->
    <link href="@Url.Content("~/Css/bootstrap.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Css/bootstrap-datetimepicker.css")" rel="stylesheet" />
    <link rel="stylesheet" href="@Url.Content("~/Css/main.min.css")">
    <link href="@Url.Content("~/Css/sitecss.css")" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.1/animate.min.css" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-2.2.3.min.js")"></script>
    <link href="@Url.Content("~/Css/sweetalert.css")" rel="stylesheet" />
    <link href="https://demos.mimiz.fr/css/jquery.loader.css" rel="stylesheet" />
    <style type="text/css">
        /*.icheckbox_flat {
            margin-top: 10px;
        }*/
        /*::-webkit-scrollbar {
            width: 12px;
        }

        ::-webkit-scrollbar-track {
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
            border-radius: 10px;
        }

        ::-webkit-scrollbar-thumb {
            border-radius: 10px;
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
        }*/
        /*body::-webkit-scrollbar {
            width: 1em;
        }

        body::-webkit-scrollbar-track {
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
        }

        body::-webkit-scrollbar-thumb {
          background-color: darkgrey;
          outline: 1px solid slategrey;
        }*/
        html {
            overflow: auto;
        }
        
        /*body {
            position: absolute;
            top: 20px;
            left: 20px;
            bottom: 20px;
            right: 20px;
            padding: 30px;
            overflow-y: scroll;
            overflow-x: hidden;
        }*/

        /* Let's get this party started */
        ::-webkit-scrollbar {
            width: 8px;
        }

        /* Track */
        ::-webkit-scrollbar-track {
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
            -webkit-border-radius: 10px;
            border-radius: 10px;
        }

        /* Handle */
        ::-webkit-scrollbar-thumb {
            -webkit-border-radius: 20px;
            border-radius: 10px;
            background: rgb(236, 240, 245);
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
        }

            ::-webkit-scrollbar-thumb:window-inactive {
                background: rgba(255,0,0,0.4);
            }

        .table tr th {
            background-color: #3f51b5;
            color: white;
        }

            .table tr th a {
                color: white;
            }

        .table {
        }

        .dtCssTxt {
            cursor: no-drop;
        }

        .nowrap {
            white-space:nowrap;
        }

        tr > td > label.control-label {
            margin-top: 0px !important;
            margin-bottom: 0px !important;
        }
        .right-elems span{
            line-height: 4;
            margin-right: 10px;
            color: #fff;
        }

        h4, .h4 {
            font-size: 18px;
            font-weight: bolder;
            margin-top: 2.5px;
            margin-bottom: -8.5px;
        }

        .box-header > h4 {
            margin-top: 0px;
            margin-bottom: 0px;
        }

        .btn-box-tool {
            background: #3f51b5;
            color: #fff;
        }

        .btn-box-tool:hover {
            color: #e4e4e4;
        }
        .uppercase{
        text-transform: uppercase;
        }

        .dtCss .input-group-addon {
            padding: 2px 12px !important;
        }
        .main-container .nav-wrap .site-nav .nav-list li.active a{
            font-weight:600;
            font-size:14px;
        }
        .main-container .nav-wrap .site-nav .nav-list > li a{
            font-weight:600;
            font-size:14px;
        }
      
    </style>
    @RenderSection("Styles", false)
</head>
@*@{
        if (Request.Cookies["NavBarCookie"] == null)
        {
            Response.Cookies["NavBarCookie"].Value = "open";
        }

        var isOpen = Request.Cookies["NavBarCookie"].Value == "open" ? true : false;
        var navBarCss = string.Empty;
        if (isOpen)
        {
            navBarCss = "nav-expand";
        }
    }*@
<body id="app" class="app off-canvas nav-expand">
    <!-- header -->
    <header class="site-head" id="site-head">
        <ul class="list-unstyled left-elems">
            <!-- nav trigger/collapse -->
            <li>
                <a href="javascript:;" class="nav-trigger ion ion-drag"></a><!--onclick="onNavBarClick();"-->
            </li>
        </ul>
                
            <ul class="list-unstyled right-elems">
                <!-- profile drop -->
                <span>@baseObj.USERID</span>
                <li class="profile-drop hidden-xs dropdown">
                    <a href="javascript:;" data-toggle="dropdown">

                        @*@if (UTILITY.ROLE_ADMIN == baseObj.ROLECODE)
                        {
                            <img src="@Url.Content("~/images/admin.jpg")" alt="admin-pic">
                        }*@

                        @if (UTILITY.ROLE_EMPLOYEE == baseObj.ROLECODE)
                        {
                            if (baseObj.DocumentDetailID != 0)
                            {
                                <img src="@Url.Content("~/Uploads/"+ baseObj.EMPLOYEEID + "/" + baseObj.DocumentDetailID + "/" + baseObj.FILENAME)" onerror="this.src='@Url.Content("~/Images/user.png")'">
                            }
                            else
                            {

                                <img src="@Url.Content("~/Images/user.png")" onerror="this.src='@Url.Content("~/images/admin.jpg")'">
                            }

                        }
                        else
                        {
                            <img src="@Url.Content("~/images/admin.jpg")" onerror="this.src='@Url.Content("~/images/user.jpg")'">
                        }

                    </a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        @*<li><a href="javascript:;"><span class="ion ion-person">&nbsp;&nbsp;</span>Profile</a></li>
                        <li><a href="javascript:;"><span class="ion ion-settings">&nbsp;&nbsp;</span>Settings</a></li>
                        <li class="divider"></li>
                        <li><a href="javascript:;"><span class="ion ion-lock-combination">&nbsp;&nbsp;</span>Lock Screen</a></li>*@
                        <li><a href="#"><i class="fa fa-globe" aria-hidden="true"></i>&nbsp;@baseObj.BRANCHNAME</a></li>
                        <li><a href="#"><i class="fa fa-user-circle-o"></i>&nbsp;@baseObj.USERID</a></li>
                        <li class="divider"></li>
                        <li><a href="@Url.Content("~/Account/LogOut")"><span class="ion ion-power">&nbsp;&nbsp;</span>LogOut</a></li>
                    </ul>
                </li>

            </ul>

</header>
    <div class="main-container clearfix">
        <!-- main-navigation -->
        <aside class="nav-wrap" id="site-nav" data-perfect-scrollbar>
            <div class="nav-head">
                <!-- site logo -->
                <a href="@Url.Content("~/Dashboard/Index")" class="site-logo text-uppercase">
                    <i class="@baseObj.GetRoleIcon()"></i>
                    <span class="text">EZY-HR</span>
                </a>
            </div>

            <!-- Site nav (vertical) -->

            <nav class="site-nav clearfix" role="navigation">

                @{
                    Html.RenderAction("Links", "Layout");
                }
            </nav>

            <!-- nav-foot -->
            <footer class="nav-foot">
                <p>2015 &copy; <span>EZY-HR</span></p>
            </footer>

        </aside>
        <!-- #end main-navigation -->
        <!-- content-here -->
        <div class="content-container" id="content">
            <!-- dashboard page -->

            @RenderBody()
            <!-- #end dashboard page -->
        </div>

    </div> <!-- #end main-container -->
    <!-- theme settings -->
    <div class="site-settings clearfix hidden-xs" style="display:none;">
        <div class="settings clearfix">
            <div class="trigger ion ion-settings left"></div>
            <div class="wrapper left">
                <ul class="list-unstyled other-settings">
                    <li class="clearfix mb10">
                        <div class="left small">Nav Horizontal</div>
                        <div class="md-switch right">
                            <label>
                                <input type="checkbox" id="navHorizontal">
                                <span>&nbsp;</span>
                            </label>
                        </div>


                    </li>
                    <li class="clearfix mb10">
                        <div class="left small">Fixed Header</div>
                        <div class="md-switch right">
                            <label>
                                <input type="checkbox" id="fixedHeader">
                                <span>&nbsp;</span>
                            </label>
                        </div>
                    </li>
                    <li class="clearfix mb10">
                        <div class="left small">Nav Full</div>
                        <div class="md-switch right">
                            <label>
                                <input type="checkbox" id="navFull">
                                <span>&nbsp;</span>
                            </label>
                        </div>
                    </li>
                </ul>
                <hr />
                <ul class="themes list-unstyled" id="themeColor">
                    <li data-theme="theme-zero" class="active"></li>
                    <li data-theme="theme-one"></li>
                    <li data-theme="theme-two"></li>
                    <li data-theme="theme-three"></li>
                    <li data-theme="theme-four"></li>
                    <li data-theme="theme-five"></li>
                    <li data-theme="theme-six"></li>
                    <li data-theme="theme-seven"></li>
                </ul>
            </div>
        </div>
    </div>
    <!-- #end theme settings -->
    <!-- Dev only -->
    <!-- Vendors -->

    <script type="text/javascript">
        var dateFormat = 'DD/MM/YYYY';
    </script>

    <script src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
    <script src="https://demos.mimiz.fr/js/jquery.loader-0.3.js"></script>
    @*<script src="@Url.Content("~/Scripts/Core/vendors.js")"></script>*@
    @*<script src="@Url.Content("~/Scripts/Core/d3.min.js")"></script>
        <script src="@Url.Content("~/Scripts/Core/c3.min.js")"></script>*@
    <script src="@Url.Content("~/Scripts/icheck.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")"></script>
    <script src="@Url.Content("~/Scripts/moment.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-datetimepicker.js")"></script>
    <script src="@Url.Content("~/Scripts/Core/screenfull.js")"></script>
    <script src="@Url.Content("~/Scripts/Core/perfect-scrollbar.min.js")"></script>
    <script src="@Url.Content("~/Scripts/Core/waves.min.js")"></script>
    <script src="@Url.Content("~/Scripts/Core/jquery.sparkline.min.js")"></script>
    <script src="@Url.Content("~/Scripts/Core/jquery.easypiechart.min.js")"></script>
    <script src="@Url.Content("~/Scripts/Core/app.js")"></script>
    <script src="@Url.Content("~/Scripts/Core/index.init.js")"></script>
    <script src="@Url.Content("~/Scripts/layout.js")"></script>
    <script src="@Url.Content("~/Scripts/Core/sweetalert.js")"></script>
    <script src="@Url.Content("~/Scripts/charts/highcharts.js")"></script>
    <script src="@Url.Content("~/Scripts/charts/series-label.js")"></script>
    <script src="@Url.Content("~/Scripts/charts/exporting.js")"></script>
   
    @RenderSection("Scripts", false)

</body>
</html>