HR.Web/Controllers/RoleRightsController.cs
using HR.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HR.Web.Helpers;

namespace HR.Web.Controllers
{
    [SessionFilter]
    [ErrorHandler]
    public class RoleRightsController : Controller
    {
        // GET: RoleRights
        public ActionResult AddRole()
        {
            return View();
        }

        public PartialViewResult NewRole(int roleId = -1)
        {
            if (roleId != -1)
            {
                using (HrDataContext dbContext = new HrDataContext())
                {
                    Role role = dbContext.Roles.Where(x => x.RoleId == roleId).FirstOrDefault();
                    return PartialView("_NewRole", role);
                }
            }
            else
                return PartialView("_NewRole", new Role { RoleId = -1 });
        }
        [HttpPost]
        public ActionResult AddRole(Role role)
        {
            using (HrDataContext dbContext = new HrDataContext())
            {
                role.ModifiedBy = "Admin";
                role.ModifiedOn = DateTime.Now;
                role.Createdby = "Admin";
                role.CreatedOn = DateTime.Now;
                role.IsActive = true;
                dbContext.Roles.Add(role);
                dbContext.SaveChanges();
            }
            return RedirectToAction("AddRole");
        }
    }
}

HR.Web/Views/RoleRights/AddRole.cshtml
<div class="page">
    <div class="page-wrap">
        <div class="panel panel-default">
            <div class="box" id="grid">
                <div class="box-header">
                    <h4>Employee Designation</h4>
                    <div class="box-tools">
                        <button class="btn btn-info btn-raised waves-effect btn-sm" type="button" onclick="EditRole(-1);"><i class="fa fa-plus"></i> Add Role</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm("AddRole", "RoleRights", FormMethod.Post, new { id = "frmRole", name = "frmRole" }))
{
    <div id="myRoleModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Role</h4>
                </div>
                <div class="modal-body" id="roleContent">

                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-info" onclick="SaveRole()">Save</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>
}
@section scripts{
    <script type="text/javascript">
        function EditRole(roleId) {
            $.ajax({
                url: '@Url.Content("~/RoleRights/NewRole?roleId=")' + roleId,
                contentType: 'text/html',
                method: 'GET',
                success: function (data) {
                    $('#myRoleModal').modal('show');
                    $('#roleContent').html('');
                    $('#roleContent').html(data);
                },
                error: function (err) {
                }
            });
        }
    </script>
}

HR.Web/Views/RoleRights/_NewRole.cshtml
@model HR.Web.Models.Role
<div class="row">
    @Html.HiddenFor(x => x.RoleId)
    @Html.HiddenFor(x => x.IsActive)
    <div class="form-group">
        <label class="col-md-4 control-label">
            <span class="pull-right">Designation</span>
        </label>
        <div class="col-md-8">
            @Html.TextBoxFor(x => x.RoleCode,
            new { @class = "form-control input-sm" })
        </div>
    </div>
</div>
<div class="row css10">
    <div class="form-group">
        <label class="col-md-4 control-label">
            <span class="pull-right">Description</span>
        </label>
        <div class="col-md-8">
            @Html.TextAreaFor(x => x.RoleDescription,
            new { @class = "form-control input-sm" })
        </div>
    </div>
</div>
<div class="row">
    <label class="col-md-4 control-label">
        <span class="pull-right">IsActive</span>
    </label>
    <div class="col-md-4">
      @Html.CheckBox("IsActive",new { id= "IsActive" })
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_flat-blue',
            radioClass: 'iradio_flat-blue',
            increaseArea: '20%' // optional
        });
    });
</script>