HR.Web/Models/EmployeeLeaveList.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaveList
    {
        public int EmployeeLeaveID { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public int BranchId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<decimal> Days { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int ManagerId { get; set; }
        public Nullable<decimal> LossOfPayDays { get; set; }
        public bool IsLossOfPay { get; set; }
        public string Session { get; set; }
    }
}

HR.Web/Models/HolidayList.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayList
    {
        public int HolidayId { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public int BranchID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int CountryId { get; set; }
    }
}

HR.Web/Models/Leave.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int LeaveId { get; set; }
        public Nullable<int> PaidLeavesPerYear { get; set; }
        public Nullable<decimal> PaidLeavesPerMonth { get; set; }
        public bool IsPaidLeaveCarryForward { get; set; }
        public Nullable<decimal> CarryForwardPerYear { get; set; }
        public Nullable<int> SickLeavesPerYear { get; set; }
        public Nullable<decimal> SickLeavesPerMonth { get; set; }
        public bool IsSickLeaveCarryForward { get; set; }
        public Nullable<decimal> CarryForwardSickLeaves { get; set; }
        public Nullable<int> CasualLeavesPerYear { get; set; }
        public Nullable<decimal> CasualLeavesPerMonth { get; set; }
        public bool IsCasualLeaveCarryForward { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<decimal> CarryForwardCasualLeave { get; set; }
    }
}

HR.Web/Models/WeekendPolicy.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekendPolicy
    {
        public int BranchId { get; set; }
        public Nullable<bool> Monday { get; set; }
        public Nullable<bool> Tuesday { get; set; }
        public Nullable<bool> Wednesday { get; set; }
        public Nullable<bool> Thursday { get; set; }
        public Nullable<bool> Friday { get; set; }
        public Nullable<bool> Saturday { get; set; }
        public Nullable<bool> Sunday { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsMondayHalfDay { get; set; }
        public Nullable<bool> IsTuesdayHalfDay { get; set; }
        public Nullable<bool> IsThursdayHalfDay { get; set; }
        public Nullable<bool> IsSaturdayHalfDay { get; set; }
        public Nullable<bool> IsSundayHalfDay { get; set; }
        public Nullable<bool> IsWednesdayHalfDay { get; set; }
        public Nullable<bool> IsFridayHalfDay { get; set; }
        public string FridaySession { get; set; }
        public string SaturdaySession { get; set; }
        public string SundaySession { get; set; }
    }
}

HR.Web/Controllers/LeaveController.cs
using HR.Web.BusinessObjects;
using HR.Web.BusinessObjects.LeaveMaster;
using HR.Web.BusinessObjects.LookUpMaster;
using HR.Web.BusinessObjects.Operation;
using HR.Web.Helpers;
using HR.Web.Models;
using HR.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;
using System.Web.Routing;
using NsExcel = Microsoft.Office.Interop.Excel;
using ClosedXML.Excel;
using System.IO;

namespace HR.Web.Controllers
{
    [SessionFilter]
    [ErrorHandler]
    public class LeaveController : BaseController
    {
        WeekendPolicyBO weekendPolicyBO = null;
        LeaveHeaderBO leaveHeaderBO = null;
        LeaveBO leaveBO = null;
        OtherLeaveBO otherLeaveBO = null;
        HolidayListBO holidayListBO = null;
        EmployeeLeaveListBO employeeLeaveListBO = null;
        LeaveTrasactionBO leaveTransactionBO = null;
        LookUpBO lookUpBo = null;
        LeaveTransBO leaveTransBO = null;
        EmployeeHeaderBO empHeaderBO = null;
        EmployeeWorkDetailBO empworkdetailsBo = null;
        public LeaveController()
        {
            weekendPolicyBO = new WeekendPolicyBO(SESSIONOBJ);
            leaveHeaderBO = new LeaveHeaderBO(SESSIONOBJ);
            leaveBO = new LeaveBO(SESSIONOBJ);
            holidayListBO = new HolidayListBO(SESSIONOBJ);
            employeeLeaveListBO = new EmployeeLeaveListBO(SESSIONOBJ);
            leaveTransactionBO = new LeaveTrasactionBO(SESSIONOBJ);
            otherLeaveBO = new OtherLeaveBO(SESSIONOBJ);
            lookUpBo = new LookUpBO(SESSIONOBJ);
            leaveTransBO = new LeaveTransBO(SESSIONOBJ);
            empHeaderBO = new EmployeeHeaderBO(SESSIONOBJ);
            empworkdetailsBo = new EmployeeWorkDetailBO(SESSIONOBJ);

        }

        // GET: Leave
        #region HolidayList
        public ActionResult HolidayList()
        {
            ViewData["RoleCode"] = ROLECODE;

            if (ROLECODE == UTILITY.ROLE_ADMIN)
            {
                holidayVm holidayVm = new holidayVm()
                {
                    calendarVM = holidayListBO.GetHolidayListByBranch(BRANCHID),
                    HolidayList = new HolidayList()
                }; return View("HolidayList", holidayVm);
            }
            else
            {
                holidayVm holidayVm = new holidayVm()
                {
                    calendarVM = holidayListBO.GetHolidayListByBranch(BRANCHID),
                    //holidayListBO.GetListByProperty(x => x.CountryId == BRANCHID).ToList()
                    HolidayList = new HolidayList()
                }; return View("HolidayList", holidayVm);
            }

        }

        public ActionResult HolidayListByBranch(int branchID = 0)
        {
            ViewData["RoleCode"] = ROLECODE;

            holidayVm holidayVm = new holidayVm()
            {
                calendarVM = holidayListBO.GetHolidayListByBranch(branchID),
                HolidayList = new HolidayList()
            };
            return View("HolidayList", holidayVm);
        }


        public ActionResult AddHoliday(int HolidayId)
        {
            ViewData["RoleCode"] = ROLECODE;
            return View("HolidayList", holidayListBO.SaveHolidayList(HolidayId));


        }

        public PartialViewResult GetHolidayList(int holidayId)
        {
            ViewData["RoleCode"] = ROLECODE;
            if (holidayId != -1)
            {
                using (var dbntx = new HrDataContext())
                {
                    var holidaylist = holidayListBO.GetById(holidayId);
                    return PartialView(holidaylist);
                }
            }
            else
            {
                var dt = DateTime.Now;
                return PartialView(new HolidayList
                {
                    Date = DateTime.Now,
                    HolidayId = -1
                });
            }

        }

        public ActionResult SaveHoliday(HolidayList holidaylist)
        {
            holidaylist.BranchID = holidaylist.CountryId;
            holidayListBO.Add(holidaylist);


            return RedirectToAction("HolidayList");

        }

        #endregion

        public ViewResult AppliedLeaveList(int page = 1, int branchid = 0, int month = 0, int year = 0)
        {
            ViewData["RoleCode"] = ROLECODE;
            var offset = Convert.ToInt32(System.Configuration.ConfigurationManager.AppSettings["appTableOffSet"]);
            int skip = (page - 1) * offset;
            List<EmpLeaveListVm> list = new List<EmpLeaveListVm>();
            using (var dbcntx = new HrDataContext())
            {

                var query = dbcntx.EmployeeHeaders.Join(
                    dbcntx.EmployeeLeaveLists,
                    a => a.EmployeeId, b => b.EmployeeId,
                    (a, b) => new { A = a, B = b })
                    .Select(x => new EmpLeaveListVm
                    {
                        EmployeeId = x.B.EmployeeId,
                        EmployeeName = x.A.FirstName + " " + x.A.LastName,
                        FromDate = x.B.FromDate,
                        ToDate = x.B.ToDate,
                        Status = x.B.Status,
                        Branchid = x.B.BranchId,
                        Reason = x.B.Reason,
                        Days = x.B.Days,
                        LeaveType = dbcntx.LookUps.Where(y => y.LookUpID == x.B.LeaveTypeId).FirstOrDefault().LookUpDescription
                    });
                var fromdate = DateTime.Now;
                if(month==0 && year == 0)
                {
                    query = query.Where(x => x.FromDate.Month == fromdate.Month);
                    query = query.Where(x => x.FromDate.Year == fromdate.Year);
                }
             else if (month != 0)
                {
                    query = query.Where(x => x.FromDate.Month == month);

                    query = query.Where(x => x.FromDate.Year == year);
                }
                   

                if (ROLECODE == UTILITY.ROLE_SUPERADMIN)
                {
                    list = query.Where(x => x.Branchid == branchid).OrderBy(x => x.Branchid).ToList();
                }
                else
                {
                    list = query.Where(x => x.Branchid == BRANCHID).ToList();
                }
            }

            var count = list.Count();
            decimal pagerLength = decimal.Divide(Convert.ToDecimal(count), Convert.ToDecimal(offset));
            HtmlTblVm<EmpLeaveListVm> HtmlTblVm = new HtmlTblVm<EmpLeaveListVm>();
            HtmlTblVm.TableData = list.Skip(skip).Take(offset).ToList();
            HtmlTblVm.TotalRows = count;
            HtmlTblVm.PageLength = Math.Ceiling(Convert.ToDecimal(pagerLength));
            HtmlTblVm.CurrentPage = page;
            return View(HtmlTblVm);
        }

        public JsonResult GetBranchLeaveData(int branchId, int pageNo)
        {

            int offSet = 10;
            int skipRows = (pageNo - 1) * offSet;
            using (var dbCntx = new HrDataContext())
            {
                var Query = dbCntx.EmployeeHeaders
                                        .Join(dbCntx.EmployeeLeaveLists,
                                        a => a.BranchId, b => b.BranchId, (a, b) => new { A = a, B = b })
                                        .Where(x => x.A.BranchId == branchId);

                var empLeaveList = Query
                                        .OrderBy(x => x.A.EmployeeId)
                                        .Skip(skipRows)
                                        .Take(offSet)
                                        .Select(x => new EmpLeaveListVm
                                        {
                                            EmployeeName = x.A.FirstName + " " + x.A.LastName,
                                            EmployeeId = x.B.EmployeeId,
                                            FromDate = x.B.FromDate,
                                            ToDate = x.B.ToDate
                                        }).ToList();

                return Json(new
                {
                    empLeaveList = empLeaveList,
                    pagerLength = Query.Count()
                }, JsonRequestBehavior.AllowGet);
            }
        }

        public void GetHolidayWeekends()
        {
            List<int> weekEnd = new List<int>();
            List<int> weekEndPolicy = new int[] { 0, 1, 2, 3, 4, 5, 6 }.ToList();
            WeekendPolicy weekendPolicy = weekendPolicyBO.GetById(BRANCHID);
            List<HolidayList> holidayList = holidayListBO.GetListByProperty(x => x.BranchID == BRANCHID).ToList();
            string[] holidaysList = new string[holidayList.Count];
            for (int i = 0; i < holidayList.Count; i++)
            {
                DateTime date = holidayList[i].Date;
                holidaysList[i] = new DateTime(date.Year, date.Month, date.Day).ToString("MM/dd/yyyy");
            }
            ViewBag.HoliDayList = holidaysList;
            if (weekendPolicy != null)
            {
                if ((!weekendPolicy.Monday.Value && !weekendPolicy.IsMondayHalfDay.Value) || !weekendPolicy.Monday.Value || weekendPolicy.IsMondayHalfDay.Value)
                {
                    weekEnd.Add(1); weekEndPolicy.Remove(1);
                }
                if ((!weekendPolicy.Tuesday.Value && !weekendPolicy.IsTuesdayHalfDay.Value) || !weekendPolicy.Tuesday.Value || weekendPolicy.IsTuesdayHalfDay.Value)
                {
                    weekEnd.Add(2); weekEndPolicy.Remove(2);
                }
                if ((!weekendPolicy.Wednesday.Value && !weekendPolicy.IsWednesdayHalfDay.Value) || !weekendPolicy.Wednesday.Value || weekendPolicy.IsWednesdayHalfDay.Value)
                {
                    weekEnd.Add(3); weekEndPolicy.Remove(3);
                }

HR.Web/Views/Leave/AppliedGrantLeaveStatus.cshtml
@model HR.Web.ViewModels.GrantLeaveListVm

@section Styles {
    <style type="text/css">
        .popover{
            max-width: 100%; 
            width: 500px;
        }
    </style>
}

@using (Html.BeginForm("ApproveLeave", "Leave", FormMethod.Post, new { id = "frmLeaveStatus", name = "frmLeaveStatus" }))
{
    <div class="page">
        <div class="panel panel-default panel-hovered panel-stacked mb10">
            <div class="box">
                <div class="box-body">
                    <div class="row">
                        <div class="form-group">
                            @Html.HiddenFor(x => x.EmployeeId)
                            @Html.HiddenFor(x => x.EmployeeLeaveID)
                            @Html.HiddenFor(x => x.useremailid)
                            <div class="col-md-3">
                                <label class="control-label pull-right">Employee Name:</label>
                            </div>
                            <div class="col-md-3">
                                <label class="control-label pull-left">@Model.Name</label>
                            </div>
                        </div>
                    </div>
                    <div class="row css10">
                        <div class="form-group">
                            <div class="col-md-3">
                                <label class="control-label pull-right">From Date:</label>
                            </div>
                            <div class="col-md-3">
                                <label class="control-label pull-left">@Model.FromDate.ToString("MM/dd/yyyy")</label>
                            </div>
                        </div>
                    </div>
                    <div class="row css10">
                        <div class="form-group">
                            <div class="col-md-3">
                                <label class="control-label pull-right">To Date:</label>
                            </div>
                            <div class="col-md-3">
                                <label class="control-label pull-left">@Model.ToDate.ToString("MM/dd/yyyy")</label>
                            </div>
                        </div>
                    </div>
                    <div class="row css10">
                        <div class="form-group">
                            <div class="col-md-3">
                                <label class="control-label pull-right">Reason:</label>
                            </div>
                            <div class="col-md-3">
                                <label class="control-label pull-left">@Model.Reason</label>
                            </div>
                        </div>
                    </div>
                    @if (Model.Status == UTILITY.LEAVEPENDING)
                    {
                        <div class="row css10">
                            <div class="col-md-3"></div>
                            <div class="col-md-9">
                                <button class="btn btn-primary btn-sm"><i class="fa fa-check"></i>Approve</button>
                                <button type="button" class="btn btn-primary btn-sm" data-toggle="popover" title="Remarks"><i class="fa fa-times"></i>Reject</button>
                            </div>
                        </div>
                    }
                    else if (Model.Status == UTILITY.LEAVEREJECTED)
                    {
                        <div class="row css10">
                            <div class="form-group">
                                <div class="col-md-3">
                                    <label class="control-label pull-right">Remarks:</label>
                                </div>
                                <div class="col-md-3">
                                    <label class="control-label pull-left">@Model.Remarks</label>
                                </div>
                            </div>
                        </div>
                    }
                    else if (Model.Status == UTILITY.LEAVEAPPROVED)
                    {
                        <div class="row css10">
                            <div class="form-group">
                                <div class="col-md-3">
                                    <label class="control-label pull-right">Status</label>
                                </div>
                                <div class="col-md-3">
                                    <label class="control-label pull-left">@UTILITY.LEAVEAPPROVED</label>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <button type="button" class="btn btn-primary btn-sm pull-right"
                        onclick="location.href='@Url.Content("~/Leave/GrantLeaveFormList")'">
                    <i class="fa fa-arrow-left"></i><b>Back</b>
                </button>
            </div>
        </div>
    </div>
    <br />
    <br />
    <br />
    <br />

}


<div id="popover" class="hide">
    <div class="row">
        <div class="form-group">
            <div class="col-md-3">Remarks:</div>
            <div class="col-md-9">                    
                @Html.TextAreaFor(x => x.Remarks, new { @class = "form-control input-sm" })
            </div>
        </div>
    </div>
    <div class="row css10">
        <div class="form-group">
            <div class="col-md-3"></div>
            <div class="col-md-9">
                <button type="button" class="btn btn-primary btn-sm" onclick="RejectLeave()"><i class="fa fa-floppy-o"></i>Save</button>
                <button type="button" class="btn btn-default btn-sm" onclick="Close()"><i class="fa fa-times"></i>Close</button>
            </div>                
        </div>
    </div>
</div>


@section Scripts
{
<script type="text/javascript">
    $(document).ready(function () {
        $('[data-toggle="popover"]').popover({
            placement: 'right',
            html: true,
            content: function () {
                var anchorText = $(this).text();
                $('#popover').find('input[id=txtContent]').attr('value', anchorText);
                return $('#popover').html();
            },
        });
       
    });
   
            //}).blur(function () {
            //    $(this).popover('hide');
            //});
        
   
    function RejectLeave() {
        $('#frmLeaveStatus').attr('action', '@Url.Content("~/Leave/RejectLeave")')

        $('#frmLeaveStatus').submit();

    }
    function Close() {
        $('[data-toggle="popover"]').popover('hide');
        }
   
</script>
}

HR.Web/Views/Leave/HolidayList.cshtml
@using Newtonsoft.Json;

@model HR.Web.ViewModels.holidayVm

@section TopStyles{

    <link href="@Url.Content("~/Css/fullcalendar.css")" rel="stylesheet" />
    <style>
        .fc-time {
            display: none;
        }

        .main-container .content-container.fixedHeader .page {
            margin-top: 0px;
        }

        page {
            padding: 0px;
        }

        .width {
            width: 80%;
        }
    </style>
}




<div class="page">
    <div class="page-wrap">
        <div class="panel panel-default panel-hovered panel-stacked mb10">
            <div class="center-block width">
                <div class="box">
                    <div class="box-header">
                        <h4>HOLIDAY LIST</h4>
                        @if (ViewData["RoleCode"].ToString() != UTILITY.ROLE_EMPLOYEE)
                        {

                            <button type="button" onclick="AddHoliday(-1)"
                                    class="btn btn-info btn-raised waves-effect btn-sm pull-right">
                                <i class="fa fa-plus"></i>Add
                            </button>

                        }
                        <div class="box-body">
                            @if (ViewData["RoleCode"].ToString() == UTILITY.ROLE_SUPERADMIN)
                            {

                                <div class="row">
                                    <div class="col-md-4">
                                        @using (Html.BeginForm("HolidayListByBranch", "Leave", FormMethod.Post, new { id = "frmHolidayList", name = "frmHolidayList" }))
                                        {
                                            @Html.DropDownListFor(x => x.BranchId, SelectListItemHelper.Branches(), "--Select--",
                            new { @class = "form-control input-sm", onchange = "getHolidayBranch(this)" })
                                        }
                                    </div>

                                </div>
                            }
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="calendar-toolbar mb20 text-center">
                                        <div class="btn-group btn-group-sm left">
                                            <button type="button" class="btn btn-default ion ion-arrow-left-c prev-btn"></button>
                                            <button type="button" class="btn btn-default ion ion-arrow-right-c next-btn"></button>
                                        </div>
                                        <button type="button" class="btn btn-default btn-sm ml15 left today-btn">Today</button>
                                        <strong class="text-uppercase current-date"></strong>
                                    </div>
                                    <div id="fullCalendar" style="z-index:9;"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>



    @using (Html.BeginForm("SaveHoliday", "Leave", FormMethod.Post, new { id = "holidayfrm", name = "holidayfrm" }))
    {
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Add Holiday</h4>
                    </div>
                    <div class="modal-body" id="modalContent">
                        @{
                            Html.RenderPartial("GetHolidayList", Model.HolidayList);
                        }
                    </div>
                    <div class="modal-footer">
                        <button id="btnsave" type="button" onclick="SaveChanges()" class="btn btn-primary btn-sm"><i class="fa fa-floppy-o"></i>Create</button>
                        <button type="button" class="btn btn-default btn-sm" onclick="location.href='@Url.Content("~/Leave/HolidayList")'"><i class="fa fa-times"></i>Close</button>
                        @if (Model.HolidayList.HolidayId != 0)
                        {
                            <button  id="btndelete" type="button" class="btn btn-danger btn-sm" onclick="location.href='@Url.Content("~/Leave/DeleteHoliday?holidayid=")'+ @Model.HolidayList.HolidayId"><i class="fa fa-trash-o"></i>Delete</button>
                        }
                        @*<button type="button" class="btn btn-danger btn-sm" onclick="location.href='@Url.Content("~/Leave/DeleteHoliday?holidayid=")'+ @Model.HolidayList.HolidayId"><i class="fa fa-trash-o"></i>Delete</button>*@
                    </div>
                </div>

            </div>
        </div>
                            }

    @section Scripts{
        <script src="@Url.Content("~/Scripts/Core/fullcalendar.min.js")"></script>


        <script type="text/javascript">

             @if(Model.HolidayList.HolidayId != -1)
             {
                 var effDt = Model.HolidayList.Date.ToString("dd/MM/yyyy");
                 if(DateTime.Parse(effDt) < DateTime.Now)
                 {
                     <text>

            $('#Date').attr('readonly', 'readonly');
            $('#Description').attr('readonly', 'readonly');
            @if (Model.HolidayList.Description != null)
                    {
                         <text>
                         $("#btnsave").remove();
                         $("#btndelete").remove();
                         </text>
                    }

            </text>
                 }
             }

            var obj = JSON.parse('@Html.Raw(JsonConvert.SerializeObject(Model.calendarVM))');
            $(function () {

                $('#li_Leave').addClass('open');
                $('#li_holidaylist').addClass('active');

                @if (Model.HolidayList != null && Model.HolidayList.HolidayId != 0)
                {
                <text>
                $('#myModal').modal('show');
                </text>
                }
            });

            function getHolidayBranch(el) {
              
                $('#frmHolidayList').submit();
                $.loader({
                    className: "blue-with-image-2",
                    content: '',
                });
            }

            function AddHoliday(holidayId) {
                //$('#Description').val('');
                //$('#Date').val('');
                //$('#CountryId').val('');
                //$('#myModal').modal('show');
                $.ajax({
                    url: '@Url.Content("~/Leave/GetHolidayList?holidayId=")' + holidayId,
                    contentType: 'text/html',
                    method: 'GET',
                    success: function (data) {
                        $('#myModal').modal('show');
                        $('#modalContent').html('');
                        $('#modalContent').html(data);
                    }
                });
            }
            function SaveChanges() {
                if ($('#holidayfrm').valid()) {
                    var dt = $('#Dt').find('input').val();
                    $('#Date').val(dt);
                    $('#holidayfrm').submit();
                    swal({
                        title: "Saved Successfully",
                        text: "",
                        closeOnConfirm: true,
                        confirmButtonText: "Ok",
                        confirmButtonClass: "btn-primary",
                        timer: 5000
                    },
                          function () {
                              $.loader({
                                  className: "blue-with-image-2",
                                  content: '',
                              });
                          })
                }
                else {
                    swal("Incorrect Inputs");
                }
            }
            $('#holidayfrm').validate({
                rules: {
                    Date: {
                        required: true,
                    },
                    Description: {
                        required: true,
                        maxlength: 20
                    },
                    CountryId: {
                        required: true
                    }
                }
            });



        </script>

        <script src="~/Scripts/Core/calendar.init.js"></script>
    }